version: '3.7'

services: 
  api:
    container_name: api
    image: contacts_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
        - postgres
    ports: 
      - "3000:3000"
    volumes: 
      - .:/app
    environment: 
      RAILS_ENV: development
  postgres:
    container_name: contacts_postgres
    image: postgres:12.1
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes: 
  postgres: